#!/bin/bash

TOKEN=
USER_ID=
OLD_PW=
NEW_PW=

BASE_URL="http://localhost:3000"
URL="${BASE_URL}/change-password/${USER_ID}"

url() {

}

json() {

#  --header "Authorization: Token token=${TOKEN}" \

}

json

# data output from curl doesn't have a trailing newline
echo
